apiVersion: v1
kind: Service
metadata:
  name: crud-app-mysql
spec:
  type: ClusterIP
  ports:
  - name: crud-app-mysql
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysql